# Generated by Django 3.2.6 on 2021-08-08 08:35

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Ten khach hang')),
                ('customer_dob', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngay sinh')),
                ('customer_adress', models.CharField(blank=True, max_length=400, null=True, verbose_name='Dia chi')),
                ('customer_phone', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Nhap so dien thoai theo dinh dang: 0123456789', regex='^\\+?\\d{8,11}$')], verbose_name='So dien thoai')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngay tao')),
            ],
            options={
                'ordering': ['customer_name'],
            },
        ),
    ]
