# Generated by Django 3.2.6 on 2021-08-08 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(error_messages={'unique': 'truong thong tin da ton tai'}, max_length=50, unique=True, verbose_name='Co so vat chat')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(error_messages={'unique': 'Loai phong da ton tai'}, max_length=50, unique=True, verbose_name='Loai phong')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Mo ta')),
                ('price', models.FloatField(verbose_name='Gia phong')),
                ('facility', models.ManyToManyField(to='room.Facility', verbose_name='Co so vat chat')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_number', models.CharField(error_messages={'unique': 'Phong da ton tai'}, max_length=30, primary_key=True, serialize=False, verbose_name='So phong')),
                ('maintenance', models.BooleanField(default=False, verbose_name='Bao tri')),
                ('availability', models.BooleanField(default=True, verbose_name='Co the su dung')),
                ('room_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.roomtype', verbose_name='Loai phong')),
            ],
            options={
                'permissions': (('can_mark_returned', 'Set book as returned'),),
            },
        ),
    ]
