# Generated by Django 3.2.6 on 2021-08-08 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('Tong dai', 'Tong dai'), ('Truc tiep', 'Truc tiep'), ('Website', 'Website'), ('Facebook', 'Facebook'), ('Intsagram', 'Intsagram')], default='Website', max_length=15, verbose_name='Hinh thuc dat phong')),
                ('no_of_adults', models.PositiveSmallIntegerField(default=1, verbose_name='So nguoi lon')),
                ('no_of_children', models.PositiveSmallIntegerField(default=0, verbose_name='So tre em')),
                ('booking_date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngay dat phong')),
                ('arrival_date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngay den')),
                ('departure_date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngay du kien di')),
                ('description', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Yeu cau cua khach hang')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='cap nhat luc')),
                ('canceled', models.BooleanField(blank=True, default=False, null=True, verbose_name='Huy dat truoc')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Nguoi thuc hien')),
            ],
            options={
                'ordering': ['arrival_date_time', 'booking_date_time'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('departure_date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngay du tra phong')),
                ('checkin_time', models.DateTimeField(auto_now_add=True, verbose_name='Thoi gian check in')),
                ('initial_amount', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Tien/ngay')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='cap nhat luc')),
                ('booking', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
                ('rooms', models.ManyToManyField(to='room.Room', verbose_name='Phong thue')),
            ],
            options={
                'ordering': ['-checkin_time'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=50, verbose_name='Dich vu')),
                ('service_price', models.FloatField(default=0, verbose_name='Gia')),
            ],
            options={
                'ordering': ['service_price', 'service_type'],
            },
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('checkout_time', models.DateTimeField(auto_now_add=True, verbose_name='Thoi gian check out')),
                ('stay_duration', models.DurationField(editable=False, null=True, verbose_name='Thoi gian luu tru')),
                ('total_amount', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Tong chi phi')),
                ('pay_amount', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Thanh tien')),
                ('discount', models.FloatField(default=0, verbose_name='Khuyen mai')),
                ('vat', models.FloatField(default=10, verbose_name='VAT')),
                ('payment_type', models.CharField(choices=[('Tien mat', 'Tien mat'), ('Chuyen khoan', 'Chuyen khoan'), ('The thanh toan', 'The thanh toan')], default='Tien mat', max_length=20, verbose_name='Hinh thuc thanh toan')),
                ('checkin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.checkin')),
                ('checkout_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Nguoi thanh toan')),
            ],
            options={
                'ordering': ['checkout_time'],
            },
        ),
        migrations.AddField(
            model_name='checkin',
            name='services',
            field=models.ManyToManyField(to='booking.Service', verbose_name='Dich vu'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Nguoi checkin'),
        ),
    ]
