# Generated by Django 3.2.6 on 2021-08-08 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(max_length=50, verbose_name='Hinh thuc dat phong')),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.bookingtype'),
        ),
    ]
