# Generated by Django 3.2.6 on 2021-08-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_booking_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='extra_fee',
            field=models.FloatField(default=0, verbose_name='Phu phi'),
        ),
    ]
