# Generated by Django 3.2.6 on 2021-09-04 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thoi gian cap nhat'),
        ),
    ]
